#!/usr/bin/env python3
"""
Vembanad Lake: visualize one window's Sentinel-2 AOI data and computed indices.
One file, no project imports. Dependencies: rasterio, numpy, matplotlib
    pip install rasterio numpy matplotlib

Shows, for a single window (e.g. A):
  1. True-color-ish RGB composite (B04/B03/B02, stretched)
  2. SCL validity mask (cloud / shadow / nodata highlighted)
  3. NDTI (turbidity), NDCI (chlorophyll), NDSSI (suspended sediment),
     MNDWI (extra water mask) (only if indexGen.py produced them for
     this window -- if the window was flagged INSUFFICIENT, this script says
     so and skips those panels rather than pretending they exist)
  4. Concentration proxies CHLA (ug/L, Mishra 2012), SPM (mg/L, Nechad),
     TURB (FNU, Dogliotti blend) when present (global calibration, not
     Vembanad-validated; for relative A/B/C comparison).
  5. Discrete labels CHLA_CLASS / TURB_CLASS / SPM_CLASS / WQ_FLAG when
     present, plus a printed + saved stats table (valid pixels only).

Usage (from the project root, same --root as download.py / indexGen.py)
  python visualize_window.py --window A
  python visualize_window.py --window A --save data/indices/A_preview.png
  python visualize_window.py --window A --save data/indices/A_preview.png --stats data/indices/A_stats.json

  Cross-date change / hotspot heatmap over 2-3 windows (one more judge image):
  python visualize.py --compare ABC --save data/indices/change_ABC.png
  python visualize.py --compare ABC --hotspot-pct 10 --write-deltas
  python visualize.py --compare AB --change-products NDTI,NDCI,NDSSI,CHLA,SPM,TURB

  Seasonal story (Premonsoon -> Monsoon -> Postmonsoon, one judge image):
  python visualize.py --seasons ABC --save data/indices/seasons_ABC.png
  python visualize.py --seasons ABC --season-names Premonsoon,Monsoon,Postmonsoon
  python visualize.py --seasons ABC --season-metric CHLA --stats-only
  python visualize.py --seasons ABC --season-mode state
  (default --season-mode change: panel 1 = baseline state, later panels = Δ vs first season;
   land stays full-brightness satellite RGB, only water is dimmed + heatmapped)

  Low-memory cloud runs (process gets OOM-killed):
  python visualize.py --window A --stats-only
  python visualize.py --window A --save preview.png --display-max-dim 800 --dpi 80
  python visualize.py --compare ABC --save change.png --display-max-dim 800 --dpi 80
"""
import argparse
import gc
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import rasterio
from rasterio.warp import reproject, Resampling
from rasterio.transform import Affine
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

CLOUD_CLASSES = [8, 9, 10]
SHADOW_CLASS = 3
NODATA_CLASS = 0


WATER_CLASS = 6

CLASS_NAMES = {
    "CHLA_CLASS": ("Masked", "Low", "Moderate", "High", "Bloom"),
    "TURB_CLASS": ("Masked", "Clear", "Slight", "Turbid", "Highly turbid"),
    "SPM_CLASS": ("Masked", "Low", "Moderate", "High", "Very high"),
    "WQ_FLAG": ("Masked", "Good", "Moderate", "Poor", "Critical"),
}

# Fallback breaks (match indexGen.py Vembanad-calibrated defaults) when
# report.json has no label_breaks (e.g. products generated by an older run).
FALLBACK_BREAKS = {"CHLA_ugL": [13.0, 14.6, 17.0], "TURB_FNU": [15.0, 17.2, 20.0],
                   "SPM_mgL": [19.0, 21.6, 25.3]}
CLASS_BREAK_KEY = {"CHLA_CLASS": "CHLA_ugL", "TURB_CLASS": "TURB_FNU", "SPM_CLASS": "SPM_mgL"}


def breaks_tag(breaks_dict, class_key):
    """Short 'b1/b2/b3' tag for a label class panel title."""
    if class_key == "WQ_FLAG":
        return "mean-of-3"
    b = breaks_dict.get(CLASS_BREAK_KEY.get(class_key, ""), [])
    return "/".join(f"{x:g}" for x in b) if b else "n/a"


DELTA_RANGES = {
    # product -> symmetric half-range for the RdBu delta panels (fixed so A/B/C comparable)
    "NDTI": 0.3, "NDCI": 0.3, "NDSSI": 0.3, "MNDWI": 0.3,
    "CHLA": 20.0, "SPM": 40.0, "TURB": 10.0,
}
DEFAULT_CHANGE_PRODUCTS = ("NDTI", "NDCI", "NDSSI", "CHLA", "SPM", "TURB")
HOTSPOT_INDEX_SET = ("NDTI", "NDCI", "NDSSI")  # standardized norm for combined magnitude


def log(msg):
    try:
        print(msg, flush=True)
    except UnicodeEncodeError:
        print(msg.encode("ascii", "replace").decode("ascii"), flush=True)


def summarize(arr, max_sample=2_000_000):
    """NaN-aware summary over valid (finite) pixels. Memory-safe.

    mean/std/min/max/n are exact (single streaming pass, no big copies).
    median/p5/p95 use a strided sample when the array is huge (accurate to
    ~1e-4 for smooth index fields, avoids a 100MB+ sort of 20M+ pixels).
    """
    finite = np.isfinite(arr)
    n_valid = int(finite.sum())
    n_total = int(arr.size)
    if n_valid == 0:
        return {"n_valid": 0, "n_total": n_total, "mean": None, "median": None,
                "std": None, "min": None, "max": None, "p5": None, "p95": None}
    # Exact moments without materializing a copy: use masked ufuncs in float64.
    vals = arr.astype(np.float64, copy=False)
    s = np.nansum(vals)
    s2 = np.nansum(vals * vals)
    mean = s / n_valid
    var = max(s2 / n_valid - mean * mean, 0.0)
    out = {
        "n_valid": n_valid,
        "n_total": n_total,
        "mean": round(float(mean), 4),
        "median": None,
        "std": round(float(np.sqrt(var)), 4),
        "min": round(float(np.nanmin(vals)), 4),
        "max": round(float(np.nanmax(vals)), 4),
        "p5": None,
        "p95": None,
    }
    # Quantiles on a strided sample (exact when small).
    stride = max(1, int(np.ceil(n_valid / max_sample)))
    sample = vals[finite][::stride]
    out["median"] = round(float(np.median(sample)), 4)
    out["p5"] = round(float(np.percentile(sample, 5)), 4)
    out["p95"] = round(float(np.percentile(sample, 95)), 4)
    del sample
    return out


def decimate(arr, max_dim):
    """Nearest-neighbour stride downsample so max(h, w) <= max_dim. No-op if small."""
    h, w = arr.shape[:2]
    m = max(h, w)
    if m <= max_dim:
        return arr
    s = int(np.ceil(m / max_dim))
    return arr[::s, ::s].copy()


def read_capped(path, max_dim, dtype=np.float32, resampling=Resampling.bilinear):
    """Read a raster decimated to max_dim for display. Returns small array."""
    with rasterio.open(path) as src:
        h, w = src.height, src.width
        m = max(h, w)
        if m <= max_dim:
            return src.read(1).astype(dtype, copy=False)
        s = int(np.ceil(m / max_dim))
        return src.read(1, out_shape=(int(np.ceil(h / s)), int(np.ceil(w / s))),
                        resampling=resampling).astype(dtype, copy=False)


def dilate_mask(mask, iters):
    """8-neighbour binary dilation without scipy (for --water-expand)."""
    out = mask.copy()
    for _ in range(max(0, int(iters))):
        padded = np.pad(out, 1, mode="constant", constant_values=False)
        grown = np.zeros_like(out)
        for dr in (-1, 0, 1):
            for dc in (-1, 0, 1):
                grown |= padded[1 + dr:1 + dr + out.shape[0], 1 + dc:1 + dc + out.shape[1]]
        out = grown
    return out


def dim_rgb(rgb, dim):
    """Dim an RGB float image for use UNDER the water heatmap (dim in 0..1)."""
    d = float(dim)
    d = min(1.0, max(0.0, d))
    return (rgb * d).astype(np.float32)


def paint_basemap(ax, rgb_bright, base_dim, water_disp):
    """Land at full satellite brightness; only water is dimmed for heatmap contrast.

    rgb_bright: display-size RGB float image (H, W, 3). water_disp: display-size
    bool mask (True = water). Land pixels keep full brightness; water pixels get
    dimmed so the heatmap on top reads clearly.
    """
    ax.imshow(rgb_bright)
    d = min(1.0, max(0.0, float(base_dim)))
    if water_disp is not None and d < 1.0:
        dim = dim_rgb(rgb_bright, d)
        mask3d = np.broadcast_to(~water_disp[:, :, None], dim.shape)
        ax.imshow(np.ma.masked_where(mask3d, dim))


def label_fractions(cls_arr, names):
    valid = cls_arr[cls_arr > 0]
    n_valid = int(valid.size)
    fractions = {}
    for code, name in enumerate(names):
        if code == 0:
            continue
        cnt = int((cls_arr == code).sum())
        fractions[name] = round(100.0 * cnt / n_valid, 2) if n_valid else 0.0
    dominant = max(fractions, key=fractions.get) if fractions and n_valid else None
    return {"n_valid": n_valid, "fractions_pct": fractions, "dominant": dominant}


def common_grid(tile_infos):
    tb = tile_infos[0]["target_bounds"]
    x0, y0, x1, y1 = tb
    w10 = int(round((x1 - x0) / 10))
    h10 = int(round((y1 - y0) / 10))
    transform10 = Affine(10, 0, x0, 0, -10, y1)
    w20, h20 = w10 // 2, h10 // 2
    transform20 = Affine(20, 0, x0, 0, -20, y1)
    return (transform10, (h10, w10)), (transform20, (h20, w20))


def mosaic_tiles(paths, out_transform, out_shape, dtype, nodata_fill=0):
    canvas = np.full(out_shape, nodata_fill, dtype=dtype)
    for p in paths:
        with rasterio.open(p) as src:
            src_arr = src.read(1)
            dst = np.full(out_shape, nodata_fill, dtype=dtype)
            reproject(source=src_arr, destination=dst,
                      src_transform=src.transform, src_crs=src.crs,
                      dst_transform=out_transform, dst_crs=src.crs,
                      resampling=Resampling.nearest, src_nodata=nodata_fill, dst_nodata=nodata_fill)
            valid = dst != nodata_fill
            canvas[valid] = dst[valid]
    return canvas


def upsample_20m_to_10m(arr20, shape10):
    h10, w10 = shape10
    out = np.repeat(np.repeat(arr20, 2, axis=0), 2, axis=1)
    return out[:h10, :w10]


def stretch(band, lo=2, hi=98, exclude=None):
    """Percentile stretch. exclude (bool, same shape) removes pixels — typically
    clouds/shadows — from the percentile sample so they don't crush land brightness.
    Excluded pixels still render (clipped), they just don't set the black/white points."""
    sample = band[::8, ::8]
    if exclude is not None:
        excl = exclude[::8, ::8] if exclude.shape == band.shape else exclude
        valid = sample[(sample > 0) & ~excl]
    else:
        valid = sample[sample > 0]
    if valid.size == 0:
        return np.zeros_like(band, dtype=np.float32)
    p_lo, p_hi = np.percentile(valid, [lo, hi])
    del sample, valid
    out = np.clip((band.astype(np.float32) - p_lo) / max(p_hi - p_lo, 1e-6), 0, 1)
    out[band == 0] = 0
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".", help="project root containing data/ (default: cwd)")
    ap.add_argument("--window", default=None, help="window label, e.g. A (single-window mode)")
    ap.add_argument("--save", default=None, help="path to save the figure (PNG). If omitted, shows interactively.")
    ap.add_argument("--stats", default=None,
                    help="path to save per-index stats JSON (valid pixels only). "
                         "Default: <indices>/<WINDOW>_<date>_stats.json, or <save-stem>_stats.json when --save is given.")
    ap.add_argument("--no-show-classes", action="store_true",
                    help="skip label panels even if class GeoTIFFs exist.")
    ap.add_argument("--include-land", action="store_true",
                    help="single-window: include land in stats/figure (default is water-only, SCL==6).")
    ap.add_argument("--water-mndwi", action="store_true",
                    help="single-window: water = SCL==6 OR MNDWI>0 (catches turbid shallows SCL calls land).")
    ap.add_argument("--water-expand", type=int, default=0,
                    help="single-window: dilate the water mask by N pixels (default: 0).")
    ap.add_argument("--no-basemap", action="store_true",
                    help="single-window/compare: disable RGB basemap under science panels (flat colors).")
    ap.add_argument("--basemap-dim", type=float, default=0.55,
                    help="dimming applied to WATER pixels under the heatmap 0..1 (default: 0.55). "
                         "Land always stays full-brightness satellite RGB.")
    ap.add_argument("--compare", default=None,
                    help="cross-date mode: window letters to compare, e.g. ABC or AB (uses official GeoTIFFs from indexGen.py).")
    ap.add_argument("--seasons", default=None,
                    help="seasonal story mode: window letters in chronological order, e.g. ABC "
                         "(one panel per window: satellite RGB land + WQ heatmap on water).")
    ap.add_argument("--season-names", default=None,
                    help="comma-separated display names for --seasons panels, e.g. Premonsoon,Monsoon,Postmonsoon "
                         "(default: the window letters).")
    ap.add_argument("--season-metric", default="WQ_FLAG",
                    help="heatmap layer for --seasons panels: WQ_FLAG, CHLA_CLASS, TURB_CLASS, SPM_CLASS "
                         "(discrete) or CHLA, SPM, TURB, NDTI, NDCI, NDSSI (continuous). Default: WQ_FLAG.")
    ap.add_argument("--season-mode", default="change", choices=["change", "state"],
                    help="seasons heatmap: 'change' (default) = panel 1 shows baseline state, later panels "
                         "show change vs the first season (Δ vs Premonsoon); 'state' = every panel shows "
                         "its own absolute state.")
    ap.add_argument("--seasons-stats", default=None,
                    help="path for seasons-mode stats JSON (default: <indices>/seasons_<LETTERS>_stats.json).")
    ap.add_argument("--hotspot-pct", type=float, default=10.0,
                    help="hotspot = top %% of combined-change magnitude per pair (default: 10).")
    ap.add_argument("--change-products", default=",".join(DEFAULT_CHANGE_PRODUCTS),
                    help="comma-separated products to difference (default: NDTI,NDCI,NDSSI,CHLA,SPM,TURB).")
    ap.add_argument("--write-deltas", action="store_true",
                    help="also write delta + hotspot GeoTIFFs next to the indices (compare mode only).")
    ap.add_argument("--change-stats", default=None,
                    help="path for compare-mode stats JSON (default: <indices>/change_<LETTERS>_stats.json).")
    ap.add_argument("--display-max-dim", type=int, default=1200,
                    help="longest side (px) for display arrays/figure; full-res is kept for stats. "
                         "Lower (e.g. 800) if the process gets OOM-killed (default: 1200).")
    ap.add_argument("--dpi", type=int, default=110,
                    help="figure DPI (default: 110; lower if OOM-killed).")
    ap.add_argument("--stats-only", action="store_true",
                    help="compute + save stats JSON and exit without rendering any figure (lowest memory).")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    data = root / "data"
    idx_dir = data / "indices"
    sel_path = data / "selected_scenes.json"

    if not sel_path.exists():
        sys.exit(f"{sel_path} not found. Run download.py first.")
    sel_doc = json.load(open(sel_path))
    selection = sel_doc.get("windows", {})

    if args.compare:
        main_compare(args, data, idx_dir, selection)
        return

    if args.seasons:
        main_seasons(args, data, idx_dir, selection)
        return

    if not args.window:
        sys.exit("Provide --window A for single-window mode, --compare ABC for change mode, "
                 "or --seasons ABC for the seasonal story.")
    main_single(args, data, idx_dir, selection)


def main_single(args, data, idx_dir, selection):
    raw = data / "raw"
    sel_path = data / "selected_scenes.json"
    label = args.window.upper()
    if label not in selection:
        sys.exit(f"Window {label} not in {sel_path}. Available: {list(selection)}")
    sel = selection[label]
    date = sel["date"]
    tiles = sel["tiles"]
    item_dirs = {t: raw / d["item_id"] for t, d in tiles.items()}

    tile_infos = []
    for tile, folder in item_dirs.items():
        info_path = folder / "download_info.json"
        if not info_path.exists():
            sys.exit(f"Missing {info_path}. Run download.py for window {label} first.")
        tile_infos.append(json.load(open(info_path)))

    (t10, shape10), (t20, shape20) = common_grid(tile_infos)

    def paths_for(band):
        ps = [item_dirs[t] / f"{band}.tif" for t in item_dirs]
        for p in ps:
            if not p.exists():
                sys.exit(f"Missing {p}. Re-run download.py for window {label}.")
        return ps

    log(f"Loading window {label} ({date}) ...")
    b02 = mosaic_tiles(paths_for("B02"), t10, shape10, np.uint16)
    b03 = mosaic_tiles(paths_for("B03"), t10, shape10, np.uint16)
    b04 = mosaic_tiles(paths_for("B04"), t10, shape10, np.uint16)
    scl20 = mosaic_tiles(paths_for("SCL"), t20, shape20, np.uint8)
    scl = upsample_20m_to_10m(scl20, shape10)
    del scl20
    gc.collect()

    cloud_mask = np.isin(scl, CLOUD_CLASSES)
    shadow_mask = scl == SHADOW_CLASS
    nodata_mask = (b04 == 0) | (scl == NODATA_CLASS)

    invalid_pct = round(100 * float((cloud_mask | shadow_mask | nodata_mask).mean()), 1)

    # --- Water mask (SCL==6), optionally OR'd with MNDWI>0, optionally dilated ---
    water_only = not args.include_land
    water_mask = np.zeros(shape10, dtype=bool)
    if water_only:
        water_mask = (scl == WATER_CLASS)
        if args.water_mndwi:
            mndwi_path = idx_dir / f"{label}_{date}_MNDWI.tif"
            if mndwi_path.exists():
                with rasterio.open(mndwi_path) as src:
                    mndwi_arr = src.read(1)
                water_mask = water_mask | (np.isfinite(mndwi_arr) & (mndwi_arr > 0))
            else:
                log("WARNING: --water-mndwi requested but MNDWI GeoTIFF missing; using SCL==6 only.")
        if args.water_expand:
            water_mask = dilate_mask(water_mask, args.water_expand)
        # Land-locked nodata/cloud stays excluded even if dilated onto it.
        water_mask = water_mask & ~(cloud_mask | shadow_mask | nodata_mask)
        water_pct = round(100 * float(water_mask.mean()), 1)
    else:
        water_mask = np.ones(shape10, dtype=bool)
        water_pct = 100.0

    max_dim = max(64, int(args.display_max_dim))
    # Display-size RGB/mask built from strided bands (stretch on small arrays only),
    # then full-res bands are freed; water_mask stays full-res for exact stats.
    # Clouds/shadows are excluded from the stretch sample so land keeps satellite brightness.
    st = max(1, int(np.ceil(max(shape10) / max_dim)))
    b02d, b03d, b04d = b02[::st, ::st], b03[::st, ::st], b04[::st, ::st]
    cloudd, shadowd, nodatad = cloud_mask[::st, ::st], shadow_mask[::st, ::st], nodata_mask[::st, ::st]
    bright_excl = cloudd | shadowd | nodatad
    rgb = np.dstack([stretch(b04d, exclude=bright_excl), stretch(b03d, exclude=bright_excl),
                     stretch(b02d, exclude=bright_excl)])
    log(f"  RGB basemap brightness: mean={rgb.mean():.3f} max={rgb.max():.3f}"
        + (" (WARNING: basemap is empty — check raw bands)" if rgb.max() <= 0 else ""))
    del b02d, b03d, b04d
    mask_rgb = np.empty((cloudd.shape[0], cloudd.shape[1], 3), dtype=np.float32)
    mask_rgb[:] = [0.85, 0.85, 0.85]  # valid = light grey
    mask_rgb[cloudd] = [1.0, 1.0, 1.0]     # cloud = white
    mask_rgb[shadowd] = [0.2, 0.2, 0.2]    # shadow = dark grey
    mask_rgb[nodatad] = [1.0, 0.0, 1.0]    # nodata = magenta
    del cloudd, shadowd, nodatad
    water_disp = water_mask[::st, ::st].copy()
    del b02, b03, b04, scl, cloud_mask, shadow_mask, nodata_mask
    gc.collect()

    # find product files, if indexGen.py already ran and window passed the gate
    idx_files = {name: idx_dir / f"{label}_{date}_{name}.tif"
                 for name in ("NDTI", "NDCI", "NDSSI", "MNDWI")}
    conc_files = {name: idx_dir / f"{label}_{date}_{name}.tif"
                  for name in ("CHLA", "SPM", "TURB")}
    class_files = {name: idx_dir / f"{label}_{date}_{name}.tif"
                   for name in ("CHLA_CLASS", "TURB_CLASS", "SPM_CLASS", "WQ_FLAG")}
    have_indices = all(p.exists() for p in idx_files.values())
    have_conc = all(p.exists() for p in conc_files.values())
    have_classes = (not args.no_show_classes) and all(p.exists() for p in class_files.values())

    report_path = idx_dir / "report.json"
    gate_status = None
    label_breaks = dict(FALLBACK_BREAKS)
    if report_path.exists():
        rep = json.load(open(report_path))
        for w in rep.get("windows", []):
            if w["window"] == label:
                gate_status = w["status"]
        if isinstance(rep.get("label_breaks"), dict):
            for k in label_breaks:
                if k in rep["label_breaks"]:
                    label_breaks[k] = list(rep["label_breaks"][k])

    # --- Load products SEQUENTIALLY: exact stats on full-res, keep only decimated display copy ---
    # Peak memory ~ one full product (~90MB) instead of all 11 (~1GB).
    products = {}   # name -> decimated display array
    stats = {"window": label, "date": date,
             "generated_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
             "scope": ("water-only (SCL==6"
                       + (" OR MNDWI>0" if (water_only and args.water_mndwi) else "")
                       + (f", dilated {args.water_expand}px" if (water_only and args.water_expand) else "")
                       + ")") if water_only else "full-AOI (land included)",
             "display_max_dim": max_dim,
             "stats_resolution": "full",
             "label_breaks": label_breaks,
             "water_pct_of_aoi": water_pct if water_only else 100.0,
             "gate_status": gate_status,
             "indices": {}, "concentrations": {}, "labels": {}}
    any_products = False
    if products_present := (have_indices or have_conc or have_classes):
        scope_tag = "WATER-ONLY" if water_only else "FULL-AOI"
        log(f"\n=== VALUES — Window {label} ({date}) | {scope_tag} "
            f"(water {water_pct}% of AOI) ===")
        log(f"{'product':<12}{'n_water':>10}{'mean':>10}{'median':>10}{'p5':>10}{'p95':>10}  dominant/fractions")
        for name in ("NDTI", "NDCI", "NDSSI", "MNDWI", "CHLA", "SPM", "TURB"):
            files = {**idx_files, **conc_files}
            if name not in files or not files[name].exists():
                continue
            with rasterio.open(files[name]) as src:
                arr = src.read(1).astype(np.float32)
            any_products = True
            arr_scope = np.where(water_mask, arr, np.nan) if water_only else arr
            s = summarize(arr_scope)
            bucket = "indices" if name in idx_files else "concentrations"
            stats[bucket][name] = s
            log(f"{name:<12}{s['n_valid']:>10}{str(s['mean']):>10}{str(s['median']):>10}"
                f"{str(s['p5']):>10}{str(s['p95']):>10}")
            products[name] = decimate(arr_scope, max_dim)
            del arr, arr_scope
            gc.collect()
        for name in ("CHLA_CLASS", "TURB_CLASS", "SPM_CLASS", "WQ_FLAG"):
            if name not in class_files or not class_files[name].exists():
                continue
            with rasterio.open(class_files[name]) as src:
                cls = src.read(1)
            any_products = True
            cls_scope = np.where(water_mask, cls, 0) if water_only else cls
            f = label_fractions(cls_scope, CLASS_NAMES[name])
            stats["labels"][name] = f
            log(f"{name:<12}{f['n_valid']:>10}  dominant={f['dominant']} fractions={f['fractions_pct']}")
            products[name] = decimate(cls_scope, max_dim)
            del cls, cls_scope
            gc.collect()
        # Resolve stats output path.
        if args.stats:
            stats_path = Path(args.stats)
        elif args.save:
            stats_path = Path(args.save).with_name(Path(args.save).stem + "_stats.json")
        else:
            stats_path = idx_dir / f"{label}_{date}_stats.json"
        stats_path.parent.mkdir(parents=True, exist_ok=True)
        stats_path.write_text(json.dumps(stats, indent=2))
        log(f"Saved stats to {stats_path}")
    else:
        log("\nNo product GeoTIFFs found — stats skipped (run indexGen.py first).")
    # Full-res water mask no longer needed; display mask takes over.
    del water_mask
    gc.collect()
    water_mask = water_disp
    del water_disp
    gc.collect()

    if args.stats_only:
        log("Stats-only mode: skipping figure.")
        plt.close("all")
        return

    # --- Figure: dynamic grid, satellite RGB land + water-only science ---
    use_basemap = not args.no_basemap
    panels = []  # (kind, key, title, cmap, vrange)
    panels.append(("rgb", None, f"Window {label} — {date}\nRGB (B04/B03/B02)", None, None))
    mask_title = (f"SCL mask — invalid {invalid_pct}%"
                  + (f", water {water_pct}%" if water_only else "")
                  + "\n(white=cloud, dark=shadow, magenta=nodata)")
    panels.append(("mask", None, mask_title, None, None))
    if have_indices:
        wt = " (water)" if water_only else ""
        panels += [
            ("cont", "NDTI", f"NDTI (turbidity){wt}", "YlOrBr", (-0.5, 0.5)),
            ("cont", "NDCI", f"NDCI (chlorophyll){wt}", "YlGn", (-0.5, 0.5)),
            ("cont", "NDSSI", f"NDSSI (sediment){wt}", "Oranges", (-1, 1)),
            ("cont", "MNDWI", "MNDWI (water, extra)", "Blues", (-1, 1)),
        ]
    if have_conc:
        wt = " (water)" if water_only else ""
        panels += [
            ("cont", "CHLA", f"CHLA (ug/L){wt}", "Greens", (0, 50)),
            ("cont", "SPM", f"SPM (mg/L){wt}", "Oranges", (0, 100)),
            ("cont", "TURB", f"TURB (FNU){wt}", "YlOrBr", (0, 30)),
        ]
    if have_classes:
        for key in ("CHLA_CLASS", "TURB_CLASS", "SPM_CLASS", "WQ_FLAG"):
            dom = stats["labels"].get(key, {}).get("dominant", "n/a")
            panels.append(("class", key, f"{key} [{breaks_tag(label_breaks, key)}]\ndom: {dom}",
                           None, None))

    if not have_indices:
        msg = (f"INSUFFICIENT DATA\n(gate status: {gate_status or 'not yet computed'})\n\n"
               f"Run indexGen.py first.\nIf this window failed the cloud/shadow "
               f"gate,\nno index maps are produced by design.")
        fig, axes = plt.subplots(1, 2, figsize=(10, 5))
        axes = list(axes)
        axes[0].imshow(rgb)
        axes[0].set_title(f"Window {label} — {date}\nRGB (B04/B03/B02)")
        axes[0].axis("off")
        axes[1].imshow(mask_rgb)
        axes[1].set_title(f"SCL mask — invalid {invalid_pct}%")
        axes[1].axis("off")
        fig.text(0.5, 0.02, msg, ha="center", fontsize=9)
        log(f"\nNo index files found for window {label} at {idx_dir}.")
        log(msg)
    else:
        from matplotlib.colors import ListedColormap, BoundaryNorm
        ncols = 6
        nrows = int(np.ceil(len(panels) / ncols))
        fig, axes = plt.subplots(nrows, ncols, figsize=(5 * ncols, 5 * nrows),
                                 squeeze=False)
        flat = list(axes.flat)
        for ax, (kind, key, title, cmap, vrange) in zip(flat, panels):
            if kind == "rgb":
                ax.imshow(rgb)
            elif kind == "mask":
                ax.imshow(mask_rgb)
            elif kind == "cont":
                arr = products[key]
                if water_only and use_basemap:
                    paint_basemap(ax, rgb, args.basemap_dim, water_mask)
                    show = np.ma.masked_where(~water_mask | ~np.isfinite(arr), arr)
                    im = ax.imshow(show, cmap=cmap, vmin=vrange[0], vmax=vrange[1])
                else:
                    im = ax.imshow(arr, cmap=cmap, vmin=vrange[0], vmax=vrange[1])
                fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
            elif kind == "class":
                arr = products[key]
                dcmap = ListedColormap([plt.get_cmap("Greys")(0.15),
                                        plt.get_cmap("Greens")(0.35),
                                        plt.get_cmap("YlOrBr")(0.45),
                                        plt.get_cmap("Oranges")(0.65),
                                        plt.get_cmap("Reds")(0.8)])
                norm = BoundaryNorm([-0.5, 0.5, 1.5, 2.5, 3.5, 4.5], dcmap.N)
                if water_only and use_basemap:
                    paint_basemap(ax, rgb, args.basemap_dim, water_mask)
                    show = np.ma.masked_where(~water_mask | (arr == 0), arr)
                    im = ax.imshow(show, cmap=dcmap, norm=norm)
                else:
                    im = ax.imshow(arr, cmap=dcmap, norm=norm)
                cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04,
                                    ticks=[0, 1, 2, 3, 4])
                cbar.ax.set_yticklabels(CLASS_NAMES[key], fontsize=7)
            ax.set_title(title, fontsize=9)
            ax.axis("off")
        for ax in flat[len(panels):]:
            ax.axis("off")

    plt.tight_layout()
    if args.save:
        out_path = Path(args.save)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(out_path, dpi=int(args.dpi), bbox_inches="tight")
        log(f"Saved figure to {out_path}")
        plt.close("all")
    else:
        plt.show()


def main_compare(args, data, idx_dir, selection):
    """Cross-date change heatmap: deltas + percentile hotspot overlays.

    Loads official indexGen.py GeoTIFFs for each window in --compare (e.g. ABC),
    computes pairwise deltas (B-A, C-B, C-A) for continuous products over
    common-valid pixels only, builds a combined standardized magnitude from
    NDTI/NDCI/NDSSI, flags the top --hotspot-pct %% as hotspots, and renders
    one judge-facing figure plus a stats JSON (and optional delta GeoTIFFs).
    """
    import matplotlib
    if args.save is None and matplotlib.get_backend().lower() == "agg":
        pass  # headless cloud: must pass --save; handled below via show() fallback

    letters = [c for c in args.compare.upper() if c in selection]
    if len(letters) < 2:
        sys.exit(f"--compare {args.compare}: need >=2 valid windows, have {letters} "
                 f"(available: {sorted(selection)})")
    products_wanted = [p.strip().upper() for p in args.change_products.split(",") if p.strip()]
    if not products_wanted:
        sys.exit("--change-products is empty.")
    hotspot_pct = float(args.hotspot_pct)
    if not (0 < hotspot_pct < 100):
        sys.exit("--hotspot-pct must be in (0, 100).")

    # Gate status per window (from report.json when available).
    gate = {}
    rep_path = idx_dir / "report.json"
    if rep_path.exists():
        try:
            rep = json.load(open(rep_path))
            for w in rep.get("windows", []):
                gate[w.get("window")] = w.get("status")
        except Exception:
            pass

    # Load official products per window, DECIMATED to display grid (memory-safe).
    # Stats below are therefore computed on the display grid; single-window mode
    # above remains the source of exact full-res per-window stats.
    max_dim = max(64, int(args.display_max_dim))
    win_dates, win_arrays, ref_profile = {}, {}, None
    missing = []
    for L in letters:
        date = selection[L]["date"]
        win_dates[L] = date
        win_arrays[L] = {}
        for prod in products_wanted:
            p = idx_dir / f"{L}_{date}_{prod}.tif"
            if not p.exists():
                missing.append(str(p))
                continue
            arr = read_capped(p, max_dim)
            win_arrays[L][prod] = arr
            if ref_profile is None and prod == products_wanted[0]:
                with rasterio.open(p) as src:
                    ref_profile = dict(crs=src.crs, transform=src.transform,
                                       width=src.width, height=src.height)
        # WQ_FLAG for class-jump panels (optional, not in change-products by default).
        wq_path = idx_dir / f"{L}_{date}_WQ_FLAG.tif"
        if wq_path.exists():
            win_arrays[L]["WQ_FLAG"] = read_capped(wq_path, max_dim, np.int16, Resampling.nearest)
            if ref_profile is None:
                with rasterio.open(wq_path) as src:
                    ref_profile = dict(crs=src.crs, transform=src.transform,
                                       width=src.width, height=src.height)
        gc.collect()
    if missing:
        log("WARNING: missing product files (window skipped for those products):")
        for m in sorted(set(missing))[:20]:
            log(f"  {m}")
    # Shape alignment check (all windows share the snapped target grid by design).
    shapes = {arr.shape for w in win_arrays.values() for arr in w.values()}
    if len(shapes) > 1:
        sys.exit(f"Product shapes differ across windows: {shapes}. "
                 f"Re-run indexGen.py so all windows share the snapped target grid.")
    if ref_profile is None:
        sys.exit("No product GeoTIFFs found for --compare windows. Run indexGen.py first.")

    # --- Water masks + RGB basemaps per window from raw (SCL==6); fallback to all-valid ---
    water_only_cmp = not getattr(args, "include_land", False)
    water_masks, rgb_maps = {}, {}
    if water_only_cmp:
        raw_dir = data / "raw"
        ref_shape = next(iter(shapes))
        for L in letters:
            try:
                sel = selection[L]
                item_dirs = {t: raw_dir / d["item_id"] for t, d in sel["tiles"].items()}
                tile_infos = []
                for _tile, folder in item_dirs.items():
                    ip = folder / "download_info.json"
                    if not ip.exists():
                        raise FileNotFoundError(str(ip))
                    tile_infos.append(json.load(open(ip)))
                (t10, shape10), (t20, shape20) = common_grid(tile_infos)
                # Products may live on a decimated grid (or full-res): resample the
                # raw-derived water/RGB to the exact product grid by nearest index.
                rh, rw = ref_shape
                full_h, full_w = shape10

                def _paths(band):
                    ps = [item_dirs[t] / f"{band}.tif" for t in item_dirs]
                    for p in ps:
                        if not p.exists():
                            raise FileNotFoundError(str(p))
                    return ps

                scl20 = mosaic_tiles(_paths("SCL"), t20, shape20, np.uint8)
                scl_w = upsample_20m_to_10m(scl20, shape10)
                del scl20
                b02w = mosaic_tiles(_paths("B02"), t10, shape10, np.uint16)
                b03w = mosaic_tiles(_paths("B03"), t10, shape10, np.uint16)
                b04w = mosaic_tiles(_paths("B04"), t10, shape10, np.uint16)
                w = (scl_w == WATER_CLASS)
                if getattr(args, "water_mndwi", False):
                    mp = idx_dir / f"{L}_{win_dates[L]}_MNDWI.tif"
                    if mp.exists():
                        marr = read_capped(mp, max(scl_w.shape))
                        w = w | (np.isfinite(marr) & (marr > 0))
                        del marr
                if getattr(args, "water_expand", 0):
                    w = dilate_mask(w, args.water_expand)
                w = w & ~(np.isin(scl_w, CLOUD_CLASSES) | (scl_w == SHADOW_CLASS)
                          | (b04w == 0) | (scl_w == NODATA_CLASS))
                # Nearest-sample raw grid -> exact product grid, then decimate
                # to display. Clouds excluded from the stretch sample so land
                # keeps satellite brightness.
                ih = np.linspace(0, full_h - 1, rh).astype(int)
                iw = np.linspace(0, full_w - 1, rw).astype(int)
                w_rs, scl_rs = w[ih][:, iw], scl_w[ih][:, iw]
                b02_rs, b03_rs, b04_rs = b02w[ih][:, iw], b03w[ih][:, iw], b04w[ih][:, iw]
                dw = decimate(w_rs, max_dim)
                st_w = max(1, int(np.ceil(max(w_rs.shape) / max_dim)))
                rs_excl = (np.isin(scl_rs[::st_w, ::st_w], CLOUD_CLASSES)
                           | (scl_rs[::st_w, ::st_w] == SHADOW_CLASS)
                           | (b04_rs[::st_w, ::st_w] == 0)
                           | (scl_rs[::st_w, ::st_w] == NODATA_CLASS))
                rgb_maps[L] = np.dstack([stretch(b04_rs[::st_w, ::st_w], exclude=rs_excl),
                                         stretch(b03_rs[::st_w, ::st_w], exclude=rs_excl),
                                         stretch(b02_rs[::st_w, ::st_w], exclude=rs_excl)])
                log(f"  [{L}] RGB basemap brightness: mean={rgb_maps[L].mean():.3f}")
                water_masks[L] = dw
                del scl_w, scl_rs, b02w, b03w, b04w, b02_rs, b03_rs, b04_rs, w, w_rs, dw
                gc.collect()
            except Exception as e:
                log(f"WARNING: water mask unavailable for window {L} ({e}); using all-valid fallback.")
                water_masks[L] = None
                rgb_maps[L] = None

    # Pairs: consecutive + first-vs-last (ABC -> B-A, C-B, C-A).
    pairs = [(letters[i], letters[i + 1]) for i in range(len(letters) - 1)]
    if len(letters) > 2:
        pairs.append((letters[0], letters[-1]))

    pair_deltas, pair_mag, pair_hot, pair_stats, pair_common_water = {}, {}, {}, {}, {}
    have_class_jump = False
    for a, b in pairs:
        tag = f"{b}-{a}"
        pair_deltas[tag] = {}
        st = {"pair": tag, "date_a": win_dates[a], "date_b": win_dates[b],
              "window_a": a, "window_b": b,
              "scope": ("common-water (SCL==6 both dates)" if water_only_cmp else "common-valid (land included)"),
              "products": {}}
        # Common water for this pair (None => fall back to finite-only).
        wa, wb = water_masks.get(a), water_masks.get(b)
        common_water = (wa & wb) if (water_only_cmp and wa is not None and wb is not None) else None
        # Reconcile shapes (bilinear decimation vs stride can differ by 1px): crop to minimum.
        if common_water is not None:
            shapes_here = {common_water.shape}
            for _p in products_wanted:
                _aa = win_arrays.get(a, {}).get(_p)
                _bb = win_arrays.get(b, {}).get(_p)
                if _aa is not None:
                    shapes_here.add(_aa.shape)
                if _bb is not None:
                    shapes_here.add(_bb.shape)
            if len(shapes_here) > 1:
                mh = min(s[0] for s in shapes_here)
                mw = min(s[1] for s in shapes_here)
                common_water = common_water[:mh, :mw]
                for _p in products_wanted:
                    if _p in win_arrays.get(a, {}):
                        win_arrays[a][_p] = win_arrays[a][_p][:mh, :mw]
                    if _p in win_arrays.get(b, {}):
                        win_arrays[b][_p] = win_arrays[b][_p][:mh, :mw]
                log(f"  {tag}: cropped rasters to common shape {(mh, mw)}.")
        st["n_common_water"] = int(common_water.sum()) if common_water is not None else None
        common_counts = []
        for prod in products_wanted:
            aa = win_arrays.get(a, {}).get(prod)
            bb = win_arrays.get(b, {}).get(prod)
            if aa is None or bb is None:
                st["products"][prod] = {"error": "missing file"}
                continue
            with np.errstate(invalid="ignore"):
                both = np.isfinite(aa) & np.isfinite(bb)
                if common_water is not None:
                    both = both & common_water
                d = np.where(both, bb - aa, np.nan)
            pair_deltas[tag][prod] = d
            v = d[np.isfinite(d)]
            common_counts.append(int(v.size))
            if v.size:
                st["products"][prod] = {
                    "n_common_valid": int(v.size),
                    "mean_delta": round(float(np.mean(v)), 4),
                    "median_delta": round(float(np.median(v)), 4),
                    "mean_abs_delta": round(float(np.mean(np.abs(v))), 4),
                    "p90_abs_delta": round(float(np.percentile(np.abs(v), 90)), 4),
                }
            else:
                st["products"][prod] = {"n_common_valid": 0, "note": "no common valid pixels"}
        # Combined standardized magnitude from the index set.
        idx_ds = [pair_deltas[tag].get(p) for p in HOTSPOT_INDEX_SET
                  if pair_deltas[tag].get(p) is not None]
        if idx_ds:
            scales = []
            for d in idx_ds:
                v = np.abs(d[np.isfinite(d)])
                scales.append(float(np.percentile(v, 95)) if v.size else 0.0)
            normed = [(d / s if s > 1e-9 else np.zeros_like(d)) for d, s in zip(idx_ds, scales)]
            stack = np.stack([np.where(np.isfinite(x), x, 0.0) for x in normed], axis=0)
            finite_any = np.stack([np.isfinite(d) for d in idx_ds], axis=0).any(axis=0)
            mag = np.sqrt((stack ** 2).sum(axis=0)).astype(np.float32)
            mag[~finite_any] = np.nan
            pair_mag[tag] = mag
            mv = mag[np.isfinite(mag)]
            if mv.size:
                thr = float(np.percentile(mv, 100.0 - hotspot_pct))
                hot = (mag >= thr) & np.isfinite(mag)
                pair_hot[tag] = hot
                st["hotspot"] = {"pct_threshold": hotspot_pct,
                                 "magnitude_threshold": round(thr, 4),
                                 "pct_area": round(100.0 * float(hot.sum()) / mv.size, 2),
                                 "n_common_valid": int(mv.size)}
            else:
                pair_hot[tag] = np.zeros(mag.shape, bool)
                st["hotspot"] = {"pct_area": 0.0, "note": "no common valid pixels"}
        else:
            st["hotspot"] = {"note": "NDTI/NDCI/NDSSI deltas unavailable"}
        # WQ_FLAG class jump (degradation >= +1) when available.
        ca = win_arrays.get(a, {}).get("WQ_FLAG")
        cb = win_arrays.get(b, {}).get("WQ_FLAG")
        if ca is not None and cb is not None:
            valid_cls = (ca > 0) & (cb > 0)
            if common_water is not None:
                valid_cls = valid_cls & common_water
            jump = np.where(valid_cls, cb.astype(np.int16) - ca.astype(np.int16), 0)
            pair_deltas[tag]["WQ_JUMP"] = jump.astype(np.int8)
            n_valid = int(valid_cls.sum())
            n_deg = int((jump >= 1).sum())
            st["wq_jump"] = {"n_common_valid": n_valid,
                             "pct_degraded": round(100.0 * n_deg / n_valid, 2) if n_valid else 0.0}
            have_class_jump = have_class_jump or (n_valid > 0)
        pair_stats[tag] = st
        pair_common_water[tag] = common_water
        n_c = min(common_counts) if common_counts else 0
        hs = st.get("hotspot", {}).get("pct_area", "n/a")
        log(f"  {tag} ({st['date_a']} -> {st['date_b']}): "
            f"n_common~{n_c} hotspot_top{hotspot_pct}%_area={hs}%")

    # --- Figure: rows = products + hotspot (+ WQ jump), cols = pairs ---
    rows = list(products_wanted) + ["HOTSPOT"]
    if have_class_jump:
        rows.append("WQ_JUMP")
    use_base_cmp = not getattr(args, "no_basemap", False)
    base_dim = float(getattr(args, "basemap_dim", 0.55))
    ncols, nrows = len(pairs), len(rows)
    fig, axes = plt.subplots(nrows, ncols, figsize=(5 * ncols, 3.8 * nrows), squeeze=False)
    for r, prod in enumerate(rows):
        for c, (a, b) in enumerate(pairs):
            tag = f"{b}-{a}"
            ax = axes[r][c]
            base = rgb_maps.get(b) if (use_base_cmp and rgb_maps.get(b) is not None) else None
            cw = pair_common_water.get(tag)
            if base is not None:
                # Bright satellite land; only common-water dimmed for contrast.
                paint_basemap(ax, base, base_dim, cw)
            if prod == "HOTSPOT":
                mag = pair_mag.get(tag)
                if mag is None:
                    ax.text(0.5, 0.5, "n/a", ha="center", va="center")
                else:
                    im = ax.imshow(mag, cmap="hot")
                    hot = pair_hot.get(tag)
                    if hot is not None and hot.any():
                        ax.contour(hot.astype(np.uint8), levels=[0.5], colors=["cyan"], linewidths=[1.0])
                    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
                hs = pair_stats[tag].get("hotspot", {}).get("pct_area", "n/a")
                ax.set_title(f"HOTSPOT {tag}\ntop {hotspot_pct:g}% area={hs}%", fontsize=9)
            elif prod == "WQ_JUMP":
                jump = pair_deltas.get(tag, {}).get("WQ_JUMP")
                if jump is None:
                    ax.text(0.5, 0.5, "n/a", ha="center", va="center")
                else:
                    im = ax.imshow(jump, cmap="RdYlGn_r", vmin=-3, vmax=3)
                    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
                deg = pair_stats[tag].get("wq_jump", {}).get("pct_degraded", "n/a")
                ax.set_title(f"WQ class jump {tag}\ndegraded={deg}% (red)", fontsize=9)
            else:
                d = pair_deltas.get(tag, {}).get(prod)
                if d is None:
                    ax.text(0.5, 0.5, "missing", ha="center", va="center")
                else:
                    full = DELTA_RANGES.get(prod)
                    if full is None:
                        vv = d[np.isfinite(d)]
                        full = float(np.percentile(np.abs(vv), 98)) if vv.size else 1.0
                    im = ax.imshow(d, cmap="coolwarm", vmin=-full, vmax=full)
                    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
                    hot = pair_hot.get(tag)
                    if hot is not None and hot.any():
                        ax.contour(hot.astype(np.uint8), levels=[0.5], colors=["black"],
                                   linewidths=[0.8], alpha=0.7)
                md = pair_stats[tag]["products"].get(prod, {}).get("mean_delta", "n/a")
                ax.set_title(f"{prod} Δ {tag}\nmean Δ={md} (black=hotspot)", fontsize=9)
            ax.axis("off")
    fig.suptitle(f"Change heatmap {''.join(letters)} "
                 f"({', '.join(f'{L}={win_dates[L]}' for L in letters)}) — "
                 f"red=increase, blue=decrease; hotspot=top {hotspot_pct:g}%"
                 + ("; water-only" if water_only_cmp else ""),
                 fontsize=13, fontweight="bold", y=0.99)
    fig.text(0.5, 0.01,
             "Deltas over common-water pixels only (SCL==6 both dates; land shows RGB map). "
             "Hotspot = top % of combined |dNDTI,dNDCI,dNDSSI| magnitude "
             "(standardized). CHLA/SPM/TURB use global calibrations, compare relatively.",
             ha="center", fontsize=9)
    plt.tight_layout(rect=[0, 0.03, 1, 0.97])

    letters_str = "".join(letters)
    if args.save:
        out_path = Path(args.save)
    else:
        out_path = idx_dir / f"change_{letters_str}.png"

    # --- Stats JSON (written before the figure so --stats-only can skip rendering) ---
    change_stats = {
        "generated_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "scope": ("common-water on display grid (SCL==6 both dates; land excluded, RGB basemap underneath)"
                  if water_only_cmp else "common-valid on display grid (land included)"),
        "display_max_dim": max_dim,
        "stats_resolution": "display (decimated); see single-window mode for exact full-res stats",
        "windows": {L: {"date": win_dates[L], "gate_status": gate.get(L)} for L in letters},
        "hotspot_pct": hotspot_pct,
        "hotspot_definition": ("top %% of combined standardized magnitude "
                               "sqrt((dNDTI/s95)^2+(dNDCI/s95)^2+(dNDSSI/s95)^2) per pair"),
        "pairs": [pair_stats[f"{b}-{a}"] for a, b in pairs],
    }
    stats_path = Path(args.change_stats) if args.change_stats else idx_dir / f"change_{letters_str}_stats.json"
    stats_path.parent.mkdir(parents=True, exist_ok=True)
    stats_path.write_text(json.dumps(change_stats, indent=2))
    log(f"Saved change stats to {stats_path}")

    if args.stats_only:
        log("Stats-only mode: skipping change figure.")
        plt.close("all")
        return

    out_path.parent.mkdir(parents=True, exist_ok=True)
    # Free per-window source arrays; only deltas/mag/hotspot + basemaps are needed below.
    del win_arrays, water_masks
    gc.collect()
    plt.savefig(out_path, dpi=int(args.dpi), bbox_inches="tight")
    log(f"Saved change figure to {out_path}")
    if args.save is None and out_path == idx_dir / f"change_{letters_str}.png":
        # default path with no explicit --save: also show interactively when possible
        try:
            plt.show()
        except Exception:
            pass
    plt.close("all")

    # --- Optional delta + hotspot GeoTIFFs ---
    if args.write_deltas:
        for a, b in pairs:
            tag = f"{b}-{a}"
            for prod, d in pair_deltas.get(tag, {}).items():
                if prod == "WQ_JUMP":
                    prof = dict(driver="GTiff", dtype="int8", count=1, width=d.shape[1],
                                height=d.shape[0], crs=ref_profile["crs"],
                                transform=ref_profile["transform"], nodata=0,
                                compress="deflate", tiled=True, blockxsize=512, blockysize=512)
                else:
                    prof = dict(driver="GTiff", dtype="float32", count=1, width=d.shape[1],
                                height=d.shape[0], crs=ref_profile["crs"],
                                transform=ref_profile["transform"], nodata=np.nan,
                                compress="deflate", predictor=3, tiled=True,
                                blockxsize=512, blockysize=512)
                out = idx_dir / f"change_{tag}_{prod}.tif"
                with rasterio.open(out, "w", **prof) as dst:
                    dst.write(d, 1)
            hot = pair_hot.get(tag)
            if hot is not None:
                prof = dict(driver="GTiff", dtype="uint8", count=1, width=hot.shape[1],
                            height=hot.shape[0], crs=ref_profile["crs"],
                            transform=ref_profile["transform"], nodata=0,
                            compress="deflate", tiled=True, blockxsize=512, blockysize=512)
                out = idx_dir / f"change_{tag}_HOTSPOT.tif"
                with rasterio.open(out, "w", **prof) as dst:
                    dst.write(hot.astype(np.uint8), 1)
        log("Wrote delta + hotspot GeoTIFFs.")


SEASON_CONT_SPECS = {
    # metric -> (cmap, vrange, unit)
    "CHLA": ("Greens", (0.0, 50.0), "ug/L"),
    "SPM": ("Oranges", (0.0, 100.0), "mg/L"),
    "TURB": ("YlOrBr", (0.0, 30.0), "FNU"),
    "NDTI": ("YlOrBr", (-0.5, 0.5), ""),
    "NDCI": ("YlGn", (-0.5, 0.5), ""),
    "NDSSI": ("Oranges", (-1.0, 1.0), ""),
    "MNDWI": ("Blues", (-1.0, 1.0), ""),
}


def main_seasons(args, data, idx_dir, selection):
    """Seasonal story: one panel per window (e.g. Premonsoon -> Monsoon -> Postmonsoon).

    Each panel shows full satellite RGB; only water pixels (SCL==6, cloud/shadow/
    nodata excluded) carry the heatmap (--season-metric, default WQ_FLAG).
    Sequential per-window load keeps memory flat; stats are exact full-res,
    the figure uses decimated display arrays.
    """
    letters = [c for c in args.seasons.upper() if c in selection]
    if len(letters) < 2:
        sys.exit(f"--seasons {args.seasons}: need >=2 valid windows, have {letters} "
                 f"(available: {sorted(selection)})")
    if args.season_names:
        names = [n.strip() or L for n, L in
                 zip(args.season_names.split(",") + [""] * len(letters), letters)]
        names = names[:len(letters)]
    else:
        names = list(letters)
    metric = str(args.season_metric).strip().upper()
    discrete = metric in CLASS_NAMES
    if not discrete and metric not in SEASON_CONT_SPECS:
        sys.exit(f"--season-metric {args.season_metric}: must be one of "
                 f"{sorted(list(CLASS_NAMES) + list(SEASON_CONT_SPECS))}.")
    season_mode = str(getattr(args, "season_mode", "state")).lower()
    if season_mode not in ("state", "change"):
        season_mode = "state"
    season_breaks = dict(FALLBACK_BREAKS)
    rep_path = idx_dir / "report.json"
    if rep_path.exists():
        try:
            _rep = json.load(open(rep_path))
            if isinstance(_rep.get("label_breaks"), dict):
                for _k in season_breaks:
                    if _k in _rep["label_breaks"]:
                        season_breaks[_k] = list(_rep["label_breaks"][_k])
        except Exception:
            pass

    max_dim = max(64, int(args.display_max_dim))
    raw_dir = data / "raw"
    panels, per_season = [], []
    for L, season in zip(letters, names):
        date = selection[L]["date"]
        entry = {"window": L, "season": season, "date": date,
                 "metric": metric, "status": None, "note": None}
        try:
            sel = selection[L]
            item_dirs = {t: raw_dir / d["item_id"] for t, d in sel["tiles"].items()}
            tile_infos = []
            for _tile, folder in item_dirs.items():
                ip = folder / "download_info.json"
                if not ip.exists():
                    raise FileNotFoundError(f"missing {ip}")
                tile_infos.append(json.load(open(ip)))
            (t10, shape10), (t20, shape20) = common_grid(tile_infos)

            def _paths(band):
                ps = [item_dirs[t] / f"{band}.tif" for t in item_dirs]
                for p in ps:
                    if not p.exists():
                        raise FileNotFoundError(f"missing {p}")
                return ps

            scl20 = mosaic_tiles(_paths("SCL"), t20, shape20, np.uint8)
            scl = upsample_20m_to_10m(scl20, shape10)
            del scl20
            b02 = mosaic_tiles(_paths("B02"), t10, shape10, np.uint16)
            b03 = mosaic_tiles(_paths("B03"), t10, shape10, np.uint16)
            b04 = mosaic_tiles(_paths("B04"), t10, shape10, np.uint16)
            water = (scl == WATER_CLASS) & ~(np.isin(scl, CLOUD_CLASSES)
                                             | (scl == SHADOW_CLASS)
                                             | (b04 == 0) | (scl == NODATA_CLASS))
            entry["water_pct_of_aoi"] = round(100 * float(water.mean()), 2)

            metric_path = idx_dir / f"{L}_{date}_{metric}.tif"
            if not metric_path.exists() and metric == "WQ_FLAG":
                fallback = idx_dir / f"{L}_{date}_CHLA_CLASS.tif"
                if fallback.exists():
                    log(f"  [{L}] WQ_FLAG missing, falling back to CHLA_CLASS.")
                    metric_path, metric = fallback, "CHLA_CLASS"
                    discrete = True
                    entry["metric"] = metric
                    entry["note"] = "WQ_FLAG missing; CHLA_CLASS shown instead"
            if not metric_path.exists():
                raise FileNotFoundError(f"missing product {metric_path} (run indexGen.py first)")
            with rasterio.open(metric_path) as src:
                marr = src.read(1)

            if discrete:
                m_scope = np.where(water, marr, 0)
                frac = label_fractions(m_scope, CLASS_NAMES[metric])
                entry.update({"n_water": frac["n_valid"], "dominant": frac["dominant"],
                              "fractions_pct": frac["fractions_pct"], "status": "OK"})
                log(f"  [{L}] {season} ({date}): water {entry['water_pct_of_aoi']}% | "
                    f"dominant={frac['dominant']} {frac['fractions_pct']}")
                disp_mask = decimate(water & (marr > 0), max_dim)
                disp_metric = decimate(np.where(water, marr, 0), max_dim)
            else:
                m_scope = np.where(water, marr.astype(np.float32), np.nan)
                s = summarize(m_scope)
                entry.update({"n_water": s["n_valid"], "mean": s["mean"], "median": s["median"],
                              "p5": s["p5"], "p95": s["p95"], "status": "OK"})
                log(f"  [{L}] {season} ({date}): water {entry['water_pct_of_aoi']}% | "
                    f"mean={s['mean']} median={s['median']}")
                disp_mask = decimate(water & np.isfinite(marr), max_dim)
                disp_metric = decimate(m_scope, max_dim)

            st = max(1, int(np.ceil(max(shape10) / max_dim)))
            scld = scl[::st, ::st]
            bright_excl = (np.isin(scld, CLOUD_CLASSES) | (scld == SHADOW_CLASS)
                           | (b04[::st, ::st] == 0) | (scld == NODATA_CLASS))
            rgb_disp = np.dstack([stretch(b04[::st, ::st], exclude=bright_excl),
                                  stretch(b03[::st, ::st], exclude=bright_excl),
                                  stretch(b02[::st, ::st], exclude=bright_excl)])
            log(f"  [{L}] RGB basemap brightness: mean={rgb_disp.mean():.3f} max={rgb_disp.max():.3f}"
                + (" (WARNING: basemap is empty — check raw bands)" if rgb_disp.max() <= 0 else ""))
            water_disp = decimate(water, max_dim)
            del scl, scld, b02, b03, b04, water, marr, m_scope
            gc.collect()
            panels.append({"season": season, "date": date, "rgb": rgb_disp,
                           "water": water_disp, "mask": disp_mask, "metric": disp_metric,
                           "entry": entry, "missing": False})
        except Exception as e:
            log(f"  [{L}] {season}: UNAVAILABLE ({e})")
            entry.update({"status": "UNAVAILABLE", "reason": str(e)})
            panels.append({"season": season, "date": selection[L]["date"], "rgb": None,
                           "water": None, "mask": None, "metric": None, "entry": entry,
                           "missing": True})
        per_season.append(entry)
        gc.collect()

    letters_str = "".join(letters)
    stats_payload = {
        "generated_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "mode": "seasons",
        "season_mode": season_mode,
        "metric": metric,
        "discrete": discrete,
        "label_breaks": season_breaks,
        "scope": "water-only (SCL==6; land shows RGB map)",
        "calibration_note": ("Global coefficients (Mishra/Nechad/Dogliotti); "
                             "compare relatively across seasons.") if not discrete else None,
        "seasons": per_season,
    }
    stats_path = (Path(args.seasons_stats) if args.seasons_stats
                  else idx_dir / f"seasons_{letters_str}_stats.json")
    stats_path.parent.mkdir(parents=True, exist_ok=True)
    stats_path.write_text(json.dumps(stats_payload, indent=2))
    log(f"Saved seasons stats to {stats_path}")

    if args.stats_only:
        log("Stats-only mode: skipping seasons figure.")
        plt.close("all")
        return

    from matplotlib.colors import ListedColormap, BoundaryNorm
    n = len(panels)
    fig, axes = plt.subplots(1, n, figsize=(6 * n, 5.5), squeeze=False)
    flat = list(axes.flat)
    base_dim = float(getattr(args, "basemap_dim", 0.55))
    last_im, last_kind = None, None
    chg_im = None  # change-mode diverging colorbar source
    for i, (ax, p) in enumerate(zip(flat, panels)):
        if p["missing"] or p["rgb"] is None:
            ax.text(0.5, 0.5, f"{p['season']}\n({p['date']})\nUNAVAILABLE", ha="center",
                    va="center", fontsize=11)
            ax.axis("off")
            continue
        # Bright satellite land; water dimmed for contrast (unless --no-basemap).
        if not args.no_basemap:
            paint_basemap(ax, p["rgb"], base_dim, p.get("water"))
        # Change mode: later panels show Δ vs the first season.
        use_change = (season_mode == "change" and i > 0
                      and panels[0].get("rgb") is not None and not panels[0].get("missing"))
        if use_change:
            first = panels[0]
            w0, m0 = first.get("water"), first.get("metric")
            w1, m1 = p.get("water"), p.get("metric")
            mh = min(m0.shape[0], m1.shape[0])
            mw = min(m0.shape[1], m1.shape[1])
            if discrete:
                v0 = (m0[:mh, :mw] > 0) & w0[:mh, :mw]
                v1 = (m1[:mh, :mw] > 0) & w1[:mh, :mw]
                both = v0 & v1
                jump = np.where(both, m1[:mh, :mw].astype(np.int16) - m0[:mh, :mw].astype(np.int16), 0)
                n_valid = int(both.sum())
                n_deg = int((jump >= 1).sum())
                deg_pct = round(100.0 * n_deg / n_valid, 2) if n_valid else 0.0
                p["entry"]["vs_first"] = {"ref_season": first["season"],
                                          "n_common_water": n_valid,
                                          "pct_degraded": deg_pct}
                log(f"  [{p['entry']['window']}] Δ vs {first['season']}: degraded={deg_pct}%")
                chg_im = ax.imshow(np.ma.masked_where(~both, jump), cmap="RdYlGn_r",
                                   vmin=-3, vmax=3)
                ax.set_title(f"{p['season']} ({p['date']})\nΔ vs {first['season']}: "
                             f"degraded {deg_pct}% (red)", fontsize=10)
            else:
                a0 = m0[:mh, :mw].astype(np.float32)
                a1 = m1[:mh, :mw].astype(np.float32)
                both = np.isfinite(a0) & np.isfinite(a1) & w0[:mh, :mw] & w1[:mh, :mw]
                d = np.where(both, a1 - a0, np.nan)
                v = d[np.isfinite(d)]
                md = round(float(np.mean(v)), 4) if v.size else None
                p["entry"]["vs_first"] = {"ref_season": first["season"],
                                          "n_common_water": int(v.size),
                                          "mean_delta": md}
                full = DELTA_RANGES.get(metric, 1.0)
                chg_im = ax.imshow(np.ma.masked_where(~both, d), cmap="coolwarm",
                                   vmin=-full, vmax=full)
                ax.set_title(f"{p['season']} ({p['date']})\nΔ vs {first['season']}: "
                             f"mean Δ={md}", fontsize=10)
            ax.axis("off")
            continue
        if discrete:
            dcmap = ListedColormap([plt.get_cmap("Greys")(0.15),
                                    plt.get_cmap("Greens")(0.35),
                                    plt.get_cmap("YlOrBr")(0.45),
                                    plt.get_cmap("Oranges")(0.65),
                                    plt.get_cmap("Reds")(0.8)])
            norm = BoundaryNorm([-0.5, 0.5, 1.5, 2.5, 3.5, 4.5], dcmap.N)
            show = np.ma.masked_where(~p["mask"], p["metric"])
            last_im = ax.imshow(show, cmap=dcmap, norm=norm)
            last_kind = "discrete"
            e = p["entry"]
            dom = e.get("dominant") or "n/a"
            crit = e.get("fractions_pct", {}).get(
                {"WQ_FLAG": "Critical", "CHLA_CLASS": "Bloom",
                 "TURB_CLASS": "Highly turbid", "SPM_CLASS": "Very high"}.get(metric, ""), None)
            extra = f"Critical {crit}%" if crit is not None else f"dom {dom}"
            ax.set_title(f"{p['season']} ({p['date']})\n{metric} [{breaks_tag(season_breaks, metric)}] "
                         f"dom: {dom} | {extra}", fontsize=10)
        else:
            cmap, vrange, unit = SEASON_CONT_SPECS[metric]
            show = np.ma.masked_where(~p["mask"], p["metric"].astype(np.float32))
            last_im = ax.imshow(show, cmap=cmap, vmin=vrange[0], vmax=vrange[1])
            last_kind = "cont"
            e = p["entry"]
            ax.set_title(f"{p['season']} ({p['date']})\n{metric} median: {e.get('median')} {unit}",
                         fontsize=10)
        ax.axis("off")
    if last_im is not None or chg_im is not None:
        plt.tight_layout(rect=[0, 0.04, 1, 0.94])
        if last_im is not None:
            if last_kind == "discrete":
                cbar = fig.colorbar(last_im, ax=flat, fraction=0.02, pad=0.02,
                                    ticks=[0, 1, 2, 3, 4], shrink=0.8)
                cbar.ax.set_yticklabels(CLASS_NAMES[metric], fontsize=9)
            else:
                _cmap, _vr, unit = SEASON_CONT_SPECS[metric]
                cbar = fig.colorbar(last_im, ax=flat, fraction=0.02, pad=0.02, shrink=0.8)
                cbar.set_label(f"{metric} ({unit})" if unit else metric, fontsize=9)
        if chg_im is not None:
            if discrete:
                cbar2 = fig.colorbar(chg_im, ax=flat, fraction=0.02, pad=0.06,
                                     ticks=[-3, -2, -1, 0, 1, 2, 3], shrink=0.8)
                cbar2.set_label(f"{metric} change vs {panels[0]['season']} "
                                "(red=degraded, green=improved)", fontsize=9)
            else:
                cbar2 = fig.colorbar(chg_im, ax=flat, fraction=0.02, pad=0.06, shrink=0.8)
                _cmap, _vr, unit = SEASON_CONT_SPECS[metric]
                cbar2.set_label(f"Δ {metric} vs {panels[0]['season']}"
                                f" ({unit})" if unit else f"Δ {metric}", fontsize=9)
    else:
        plt.tight_layout(rect=[0, 0.04, 1, 0.94])
    mode_tag = (f"panel 1 = {metric} baseline, later panels = change vs {panels[0]['season']}"
                if season_mode == "change" else f"{metric} state per season")
    br_txt = (f"breaks CHLA {breaks_tag(season_breaks, 'CHLA_CLASS')} ug/L / "
              f"TURB {breaks_tag(season_breaks, 'TURB_CLASS')} FNU / "
              f"SPM {breaks_tag(season_breaks, 'SPM_CLASS')} mg/L")
    fig.suptitle(f"{' → '.join(p['season'] for p in panels)} — {mode_tag}; land as satellite RGB",
                 fontsize=14, fontweight="bold", y=1.0)
    fig.text(0.5, 0.01,
             f"Water-only (SCL==6; cloud/shadow/nodata excluded). {br_txt}. "
             "Same breaks/colors every panel — compare directly. "
             "Global calibration: relative comparison only.",
             ha="center", fontsize=9)
    out_path = Path(args.save) if args.save else idx_dir / f"seasons_{letters_str}.png"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_path, dpi=int(args.dpi), bbox_inches="tight")
    log(f"Saved seasons figure to {out_path}")
    plt.close("all")


if __name__ == "__main__":
    main()